# Generated by Django 3.2.4 on 2021-06-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.IntegerField()),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('business_name', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=250)),
                ('school', models.CharField(max_length=250)),
                ('level', models.PositiveIntegerField()),
                ('interest', models.CharField(max_length=250)),
            ],
        ),
    ]
