# Generated by Django 3.2 on 2021-06-23 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerregistration',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employerregistration',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='country',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='level',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{8,15}$')]),
        ),
    ]
