# Generated by Django 3.2.4 on 2021-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='employerregistration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employerregistration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employerregistration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employerregistration',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='occupation',
        ),
    ]
