# Generated by Django 3.2.4 on 2021-06-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210626_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalregistration',
            old_name='occupation',
            new_name='user_type',
        ),
    ]
