# Generated by Django 3.2.4 on 2021-06-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_occupation_generalregistration_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='interest',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='level',
            field=models.CharField(max_length=250),
        ),
    ]
