# Generated by Django 3.2.4 on 2021-06-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210626_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='interest',
            new_name='skills',
        ),
    ]
