# Generated by Django 3.2.4 on 2021-06-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_studentregistration_general_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregistration',
            name='general_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.generalregistration'),
        ),
    ]
