# Generated by Django 3.2.4 on 2021-06-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_employerregistration_general_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerregistration',
            name='general_info',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='general_info',
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='first_name',
            field=models.CharField(default='Daniel', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerregistration',
            name='last_name',
            field=models.CharField(default='Sumah', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='first_name',
            field=models.CharField(default='Daniel', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='last_name',
            field=models.CharField(default='Sumah', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerregistration',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='employerregistration',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='GeneralRegistration',
        ),
    ]
