# Generated by Django 3.2.4 on 2021-07-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210623_0915'),
        ('backend', '0008_auto_20210630_1741'),
    ]

    operations = [
    ]
