# Generated by Django 3.2.4 on 2021-07-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_merge_0002_auto_20210623_0915_0008_auto_20210630_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerregistration',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employerregistration',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='level',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
