# Generated by Django 3.2.5 on 2021-07-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210704_2113'),
        ('backend', '0011_studentprofile_user'),
    ]

    operations = [
    ]
