# Generated by Django 3.0.8 on 2021-07-05 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_merge_20210705_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWorkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_sample', models.FileField(blank=True, null=True, upload_to='')),
                ('tags', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.StudentRegistration')),
            ],
        ),
    ]
