# Generated by Django 3.2.5 on 2021-07-05 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0013_auto_20210705_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('interest', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_handle', models.CharField(max_length=100)),
                ('linkedin_link', models.CharField(max_length=500)),
                ('employer_reg_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.employerregistration')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
