# Generated by Django 3.2.5 on 2021-07-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_employerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
