# Generated by Django 3.2.5 on 2021-07-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_studentworkpost'),
        ('backend', '0015_auto_20210706_0936'),
    ]

    operations = [
    ]
