# Generated by Django 3.2.5 on 2021-07-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_merge_0013_studentworkpost_0015_auto_20210706_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentworkpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
