# Generated by Django 3.2.4 on 2021-07-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210704_0919'),
        ('backend', '0017_alter_studentworkpost_id'),
    ]

    operations = [
    ]
